# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 推送test

on:
  schedule:
    # 设置启动时间，为 UTC 时间, UTC24点 对应北京时间早8点
    - cron : '25 07 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Ten-Abstinence-Days Notification
      run: |
        python test.py
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        USER_ID: ${{ secrets.USER_ID }}
        TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
